---
name: "Bug report"
description: "Report a bug with the integration"
labels: "Bug"
body:
- type: markdown
  attributes:
    value: Before you open a new issue, search through the existing issues to see if others have had the same problem.
- type: textarea
  attributes:
    label: "Versions"
    description: "Provide the versions of Home Assistant and the import statisticsintegration you are using."
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have read the troubleshooting tips linked in the README.
        required: true
      - label: If there are problems with spikes for counters, I have read "Counter Statistics Explained" linked in the README.
        required: true
      - label: I have enabled debug logging for my installation.
        required: true
      - label: I have filled out the issue template to the best of my ability.
        required: true
- type: textarea
  attributes:
    label: "Describe the issue"
    description: "A clear and concise description of what the issue is."
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction steps
    description: "Without steps to reproduce, it will be hard to fix. It is very important that you fill out this part. Issues without it will be closed."
    value: |
      1.
      2.
      3.
      ...
  validations:
    required: true
- type: textarea
  attributes:
    label: "Debug logs"
    description: "To enable and fetch debug logs, see the [Debug Logging Guide](https://github.com/klausj1/homeassistant-statistics/blob/main/docs/user/debug-logging.md)."
    render: text
  validations:
    required: true
