name: "Tests"

on:
  push:
  pull_request:

jobs:
  tests:
    name: "Run Tests"
    permissions:
      contents: read
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6.0.2"

      - name: "Set up Python"
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.13.2"
          cache: "pip"

      - name: "Install dependencies"
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r requirements.test.txt

      - name: "Run tests"
        run: pytest -v
